nameOverride: ingress-nginx
controller:
  config:
    use-forwarded-headers: true
    log-format-escape-json: true
    log-format-upstream: '{"timestamp": "$time_iso8601", "requestID": "$req_id", "httpRequest": {"timeLocal": "$time_local", "httpReferer": "$http_referer", "requestMethod": "$request_method", "host": "$host", "requestUri": "$request_uri", "status": $status, "requestTime": $request_time, "bodyBytesSent": $body_bytes_sent, "requestSize": $request_length, "proxyUpstreamName": "$proxy_upstream_name", "upstreamStatus": $upstream_status, "upstreamAddr": "$upstream_addr", "upstreamResponseSize": $upstream_response_length, "httpUserAgent": "$http_user_agent","remoteAddr": "$remote_addr", "remoteUser": "$remote_user", "upstreamResponseTime": $upstream_response_time, "serverProtocol": "$server_protocol"}}'

  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 60

  service:
    enabled: true
    ports:
      http: 80
      https: 443

    targetPorts:
      http: http
      https: https

    type: LoadBalancer
    nodePorts:
      http: 32000
      https: 32443

  metrics:
    port: 10254
    enabled: true

    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"